version: '3.6'

networks:
  backend:

services:
  jenkins:
    image: nc/jenkins-master-dev:latest
    build:
      context: ./master
      dockerfile: Dockerfile
      args:
        jenkins_master_pass: 123
        jenkins_slave_port: 50000
        jenkins_slave_pass: 123
        jenkins_config_repo_provider: git
        jenkins_config_repo_url: git@github.com:mikand13/dockerized-jenkins-accelerator-config.git
    shm_size: '40gb'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
    restart: always
  jenkins-nginx:
    image: nc/jenkins-master-nginx-dev:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - jenkins
    networks:
      backend:
    ports:
      - "80:80"
      - "443:443"
    restart: always
  jenkins-build-slave:
    image: nc/jenkins-standard-build-slave-dev:latest
    build:
      context: slaves/standard_build_slave
      dockerfile: Dockerfile
      args:
        jenkins_slave_pass: 123
        agent_name: standard_build
        cli_url: http://jenkins:8080
        jnlp_user: jenkins-slave
        labels: standard_build
    shm_size: '20gb'
    depends_on:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
    restart: always
  jenkins-deploy-slave:
    image: nc/jenkins-deploy-slave-dev:latest
    build:
      context: slaves/deploy_slave
      dockerfile: Dockerfile
      args:
        jenkins_slave_pass: 123
        agent_name: deploy
        cli_url: http://jenkins:8080
        jnlp_user: jenkins-slave
        labels: deploy
    depends_on:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
    restart: always